services:
  moodleserver:
    container_name: moodle
    image: bitnami/moodle:4.4.3
    depends_on:
      moodledb:
        condition: service_healthy
    ports:
      - 80:8080
      - 443:8443
    environment:
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
      - MOODLE_SITE_NAME=${MOODLE_SITE_NAME}
      - MOODLE_LANG=${MOODLE_LANG}
      - MOODLE_DATABASE_USER=${DB_USER} 
      - MOODLE_DATABASE_PASSWORD=${DB_PASSWORD} 
      - MOODLE_DATABASE_NAME=${DB_NAME} 
      - MOODLE_DATABASE_HOST=${DB_HOST}
      - MOODLE_DATABASE_PORT_NUMBER=${DB_PORT}
    volumes:
      - moodlesrv_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    networks:
      - moodle-network
  moodledb:
    container_name: moodledb
    image: bitnami/mariadb:11.5.2
    environment:
      - MARIADB_USER=${DB_USER} 
      - MARIADB_PASSWORD=${DB_PASSWORD} 
      - MARIADB_DATABASE=${DB_NAME} 
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - moodledb_data:/bitnami/mariadb
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p'${DB_ROOT_PASSWORD}'"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - moodle-network

volumes:
  moodledb_data:
  moodlesrv_data:
  moodledata_data:
    
networks:
  moodle-network:
    driver: bridge
